<?php
/**
 * CsnAuthorization - Coolcsn Zend Framework 2 Authorization Module
 * 
 * @link https://github.com/coolcsn/CsnAuthorization for the canonical source repository
 * @copyright Copyright (c) 2005-2013 LightSoft 2005 Ltd. Bulgaria
 * @license https://github.com/coolcsn/CsnAuthorization/blob/master/LICENSE BSDLicense
 * @author Stoyan Cheresharov <stoyan@coolcsn.com>
 * @author Stoyan Revov <st.revov@gmail.com>
 * @author Martin Briglia <martin@mgscreativa.com>
 */

$flashMessenger = $this->flashMessenger()
  ->setMessageOpenFormat(
  '<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
  ->setMessageSeparatorString('</li><li>')
  ->setMessageCloseString('</li></ul></div>');

?>

<div class="container wrapper">
 <?php echo $flashMessenger->render('error',   array('alert', 'alert-dismissable', 'alert-danger')); ?>
 <?php echo $flashMessenger->render('info',    array('alert', 'alert-dismissable', 'alert-info')); ?>
 <?php echo $flashMessenger->render('default', array('alert', 'alert-dismissable', 'alert-warning')); ?>
 <?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
</div>
<h1>
  <?php echo $this->translate('Resources Admin Table') ?>
</h1>
<a class="btn btn-success" href="<?php echo $this->url('resource-admin', array('action' => 'create-resource')); ?>">
  <?php echo $this->translate('Create Resource') ?>
</a>
<hr />
<div class="table-responsive">
  <table class="resources-list table table-striped table-condensed table-hover">
    <thead>
      <tr>
        <th>Id</th>
        <th><?php echo $this->translate('Name') ?></th>
        <th><?php echo $this->translate('Actions') ?></th>
      </tr>
    </thead>
    <?php
      foreach ($resources as $resource) {
    ?>
      <tr>
        <td><?php  echo $resource->getId(); ?></td>
        <td>
          <a class="name" href="<?php echo $this->url('resource-admin', array('action' => 'edit-resource', 'id' => $resource->getId())); ?>">
            <?php echo $resource->getDescription() ?>
          </a>
          <span class="subtext">(<?php echo $resource->getName() ?>)</span>
        </td>
        <td class="delete-cell">
          <a href="<?php echo $this->url('resource-admin', array('action'=>'edit-resource', 'id' => $resource->getId()));?>">
            <?php echo $this->translate('Edit') ?>
          </a> | 
          <a href="<?php echo $this->url('resource-admin', array('action'=>'delete-resource', 'id' => $resource->getId()));?>" onclick="return confirm('<?php echo $this->translate('Do you really want to delete this resource?') ?>')">
            <?php echo $this->translate('Delete') ?>
          </a>
        </td>        
      </tr>
      <?php
      }
      ?>
  </table>
</div>
